/*
WhatsAPI Go

Testing MiscellaneousApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_openapi_MiscellaneousApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test MiscellaneousApiService InstancesInstanceKeyMiscProfilePicGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var instanceKey string

        resp, httpRes, err := apiClient.MiscellaneousApi.InstancesInstanceKeyMiscProfilePicGet(context.Background(), instanceKey).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test MiscellaneousApiService InstancesInstanceKeyMiscUserInfoPost", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var instanceKey string

        resp, httpRes, err := apiClient.MiscellaneousApi.InstancesInstanceKeyMiscUserInfoPost(context.Background(), instanceKey).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
