/*
WhatsAPI Go

Testing BusinessManagementApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package WhatsAPI

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_WhatsAPI_BusinessManagementApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test BusinessManagementApiService InstancesInstanceKeyBusinessCatalogGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var instanceKey string

        resp, httpRes, err := apiClient.BusinessManagementApi.InstancesInstanceKeyBusinessCatalogGet(context.Background(), instanceKey).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
