/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package WhatsAPI

import (
	"encoding/json"
)

// GroupUpdateNamePayload struct for GroupUpdateNamePayload
type GroupUpdateNamePayload struct {
	Name *string `json:"name,omitempty"`
}

// NewGroupUpdateNamePayload instantiates a new GroupUpdateNamePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupUpdateNamePayload() *GroupUpdateNamePayload {
	this := GroupUpdateNamePayload{}
	return &this
}

// NewGroupUpdateNamePayloadWithDefaults instantiates a new GroupUpdateNamePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupUpdateNamePayloadWithDefaults() *GroupUpdateNamePayload {
	this := GroupUpdateNamePayload{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GroupUpdateNamePayload) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupUpdateNamePayload) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GroupUpdateNamePayload) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GroupUpdateNamePayload) SetName(v string) {
	o.Name = &v
}

func (o GroupUpdateNamePayload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableGroupUpdateNamePayload struct {
	value *GroupUpdateNamePayload
	isSet bool
}

func (v NullableGroupUpdateNamePayload) Get() *GroupUpdateNamePayload {
	return v.value
}

func (v *NullableGroupUpdateNamePayload) Set(val *GroupUpdateNamePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupUpdateNamePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupUpdateNamePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupUpdateNamePayload(val *GroupUpdateNamePayload) *NullableGroupUpdateNamePayload {
	return &NullableGroupUpdateNamePayload{value: val, isSet: true}
}

func (v NullableGroupUpdateNamePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupUpdateNamePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


