/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package WhatsAPI

import (
	"encoding/json"
	"os"
)

// UploadMediaRequest struct for UploadMediaRequest
type UploadMediaRequest struct {
	// Media file
	File *os.File `json:"file"`
}

// NewUploadMediaRequest instantiates a new UploadMediaRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadMediaRequest(file *os.File) *UploadMediaRequest {
	this := UploadMediaRequest{}
	this.File = file
	return &this
}

// NewUploadMediaRequestWithDefaults instantiates a new UploadMediaRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadMediaRequestWithDefaults() *UploadMediaRequest {
	this := UploadMediaRequest{}
	return &this
}

// GetFile returns the File field value
func (o *UploadMediaRequest) GetFile() *os.File {
	if o == nil {
		var ret *os.File
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *UploadMediaRequest) GetFileOk() (**os.File, bool) {
	if o == nil {
    return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *UploadMediaRequest) SetFile(v *os.File) {
	o.File = v
}

func (o UploadMediaRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["file"] = o.File
	}
	return json.Marshal(toSerialize)
}

type NullableUploadMediaRequest struct {
	value *UploadMediaRequest
	isSet bool
}

func (v NullableUploadMediaRequest) Get() *UploadMediaRequest {
	return v.value
}

func (v *NullableUploadMediaRequest) Set(val *UploadMediaRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadMediaRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadMediaRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadMediaRequest(val *UploadMediaRequest) *NullableUploadMediaRequest {
	return &NullableUploadMediaRequest{value: val, isSet: true}
}

func (v NullableUploadMediaRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadMediaRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


