/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"os"
)

// InstancesInstanceKeySendVideoPostRequest struct for InstancesInstanceKeySendVideoPostRequest
type InstancesInstanceKeySendVideoPostRequest struct {
	// Video file
	File *os.File `json:"file"`
}

// NewInstancesInstanceKeySendVideoPostRequest instantiates a new InstancesInstanceKeySendVideoPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstancesInstanceKeySendVideoPostRequest(file *os.File) *InstancesInstanceKeySendVideoPostRequest {
	this := InstancesInstanceKeySendVideoPostRequest{}
	this.File = file
	return &this
}

// NewInstancesInstanceKeySendVideoPostRequestWithDefaults instantiates a new InstancesInstanceKeySendVideoPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstancesInstanceKeySendVideoPostRequestWithDefaults() *InstancesInstanceKeySendVideoPostRequest {
	this := InstancesInstanceKeySendVideoPostRequest{}
	return &this
}

// GetFile returns the File field value
func (o *InstancesInstanceKeySendVideoPostRequest) GetFile() *os.File {
	if o == nil {
		var ret *os.File
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *InstancesInstanceKeySendVideoPostRequest) GetFileOk() (**os.File, bool) {
	if o == nil {
    return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *InstancesInstanceKeySendVideoPostRequest) SetFile(v *os.File) {
	o.File = v
}

func (o InstancesInstanceKeySendVideoPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["file"] = o.File
	}
	return json.Marshal(toSerialize)
}

type NullableInstancesInstanceKeySendVideoPostRequest struct {
	value *InstancesInstanceKeySendVideoPostRequest
	isSet bool
}

func (v NullableInstancesInstanceKeySendVideoPostRequest) Get() *InstancesInstanceKeySendVideoPostRequest {
	return v.value
}

func (v *NullableInstancesInstanceKeySendVideoPostRequest) Set(val *InstancesInstanceKeySendVideoPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInstancesInstanceKeySendVideoPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInstancesInstanceKeySendVideoPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstancesInstanceKeySendVideoPostRequest(val *InstancesInstanceKeySendVideoPostRequest) *NullableInstancesInstanceKeySendVideoPostRequest {
	return &NullableInstancesInstanceKeySendVideoPostRequest{value: val, isSet: true}
}

func (v NullableInstancesInstanceKeySendVideoPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstancesInstanceKeySendVideoPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


