/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package WhatsAPI

import (
	"encoding/json"
)

// StructsContactMessagePayloadVcard struct for StructsContactMessagePayloadVcard
type StructsContactMessagePayloadVcard struct {
	FullName *string `json:"full_name,omitempty"`
	Organization *string `json:"organization,omitempty"`
	Phone *string `json:"phone,omitempty"`
}

// NewStructsContactMessagePayloadVcard instantiates a new StructsContactMessagePayloadVcard object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStructsContactMessagePayloadVcard() *StructsContactMessagePayloadVcard {
	this := StructsContactMessagePayloadVcard{}
	return &this
}

// NewStructsContactMessagePayloadVcardWithDefaults instantiates a new StructsContactMessagePayloadVcard object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStructsContactMessagePayloadVcardWithDefaults() *StructsContactMessagePayloadVcard {
	this := StructsContactMessagePayloadVcard{}
	return &this
}

// GetFullName returns the FullName field value if set, zero value otherwise.
func (o *StructsContactMessagePayloadVcard) GetFullName() string {
	if o == nil || isNil(o.FullName) {
		var ret string
		return ret
	}
	return *o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StructsContactMessagePayloadVcard) GetFullNameOk() (*string, bool) {
	if o == nil || isNil(o.FullName) {
    return nil, false
	}
	return o.FullName, true
}

// HasFullName returns a boolean if a field has been set.
func (o *StructsContactMessagePayloadVcard) HasFullName() bool {
	if o != nil && !isNil(o.FullName) {
		return true
	}

	return false
}

// SetFullName gets a reference to the given string and assigns it to the FullName field.
func (o *StructsContactMessagePayloadVcard) SetFullName(v string) {
	o.FullName = &v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *StructsContactMessagePayloadVcard) GetOrganization() string {
	if o == nil || isNil(o.Organization) {
		var ret string
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StructsContactMessagePayloadVcard) GetOrganizationOk() (*string, bool) {
	if o == nil || isNil(o.Organization) {
    return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *StructsContactMessagePayloadVcard) HasOrganization() bool {
	if o != nil && !isNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given string and assigns it to the Organization field.
func (o *StructsContactMessagePayloadVcard) SetOrganization(v string) {
	o.Organization = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *StructsContactMessagePayloadVcard) GetPhone() string {
	if o == nil || isNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StructsContactMessagePayloadVcard) GetPhoneOk() (*string, bool) {
	if o == nil || isNil(o.Phone) {
    return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *StructsContactMessagePayloadVcard) HasPhone() bool {
	if o != nil && !isNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *StructsContactMessagePayloadVcard) SetPhone(v string) {
	o.Phone = &v
}

func (o StructsContactMessagePayloadVcard) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.FullName) {
		toSerialize["full_name"] = o.FullName
	}
	if !isNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	if !isNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	return json.Marshal(toSerialize)
}

type NullableStructsContactMessagePayloadVcard struct {
	value *StructsContactMessagePayloadVcard
	isSet bool
}

func (v NullableStructsContactMessagePayloadVcard) Get() *StructsContactMessagePayloadVcard {
	return v.value
}

func (v *NullableStructsContactMessagePayloadVcard) Set(val *StructsContactMessagePayloadVcard) {
	v.value = val
	v.isSet = true
}

func (v NullableStructsContactMessagePayloadVcard) IsSet() bool {
	return v.isSet
}

func (v *NullableStructsContactMessagePayloadVcard) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStructsContactMessagePayloadVcard(val *StructsContactMessagePayloadVcard) *NullableStructsContactMessagePayloadVcard {
	return &NullableStructsContactMessagePayloadVcard{value: val, isSet: true}
}

func (v NullableStructsContactMessagePayloadVcard) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStructsContactMessagePayloadVcard) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


