/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package WhatsAPI

import (
	"encoding/json"
	"os"
)

// SetGroupPictureRequest struct for SetGroupPictureRequest
type SetGroupPictureRequest struct {
	// Group picture in JPEG
	File *os.File `json:"file"`
}

// NewSetGroupPictureRequest instantiates a new SetGroupPictureRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetGroupPictureRequest(file *os.File) *SetGroupPictureRequest {
	this := SetGroupPictureRequest{}
	this.File = file
	return &this
}

// NewSetGroupPictureRequestWithDefaults instantiates a new SetGroupPictureRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetGroupPictureRequestWithDefaults() *SetGroupPictureRequest {
	this := SetGroupPictureRequest{}
	return &this
}

// GetFile returns the File field value
func (o *SetGroupPictureRequest) GetFile() *os.File {
	if o == nil {
		var ret *os.File
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *SetGroupPictureRequest) GetFileOk() (**os.File, bool) {
	if o == nil {
    return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *SetGroupPictureRequest) SetFile(v *os.File) {
	o.File = v
}

func (o SetGroupPictureRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["file"] = o.File
	}
	return json.Marshal(toSerialize)
}

type NullableSetGroupPictureRequest struct {
	value *SetGroupPictureRequest
	isSet bool
}

func (v NullableSetGroupPictureRequest) Get() *SetGroupPictureRequest {
	return v.value
}

func (v *NullableSetGroupPictureRequest) Set(val *SetGroupPictureRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetGroupPictureRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetGroupPictureRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetGroupPictureRequest(val *SetGroupPictureRequest) *NullableSetGroupPictureRequest {
	return &NullableSetGroupPictureRequest{value: val, isSet: true}
}

func (v NullableSetGroupPictureRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetGroupPictureRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


