/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package WhatsAPI

import (
	"encoding/json"
	"os"
)

// SendDocumentRequest struct for SendDocumentRequest
type SendDocumentRequest struct {
	// Document file
	File *os.File `json:"file"`
}

// NewSendDocumentRequest instantiates a new SendDocumentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendDocumentRequest(file *os.File) *SendDocumentRequest {
	this := SendDocumentRequest{}
	this.File = file
	return &this
}

// NewSendDocumentRequestWithDefaults instantiates a new SendDocumentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendDocumentRequestWithDefaults() *SendDocumentRequest {
	this := SendDocumentRequest{}
	return &this
}

// GetFile returns the File field value
func (o *SendDocumentRequest) GetFile() *os.File {
	if o == nil {
		var ret *os.File
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *SendDocumentRequest) GetFileOk() (**os.File, bool) {
	if o == nil {
    return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *SendDocumentRequest) SetFile(v *os.File) {
	o.File = v
}

func (o SendDocumentRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["file"] = o.File
	}
	return json.Marshal(toSerialize)
}

type NullableSendDocumentRequest struct {
	value *SendDocumentRequest
	isSet bool
}

func (v NullableSendDocumentRequest) Get() *SendDocumentRequest {
	return v.value
}

func (v *NullableSendDocumentRequest) Set(val *SendDocumentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSendDocumentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSendDocumentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendDocumentRequest(val *SendDocumentRequest) *NullableSendDocumentRequest {
	return &NullableSendDocumentRequest{value: val, isSet: true}
}

func (v NullableSendDocumentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendDocumentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


