/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package WhatsAPI

import (
	"encoding/json"
)

// ContactMessagePayload struct for ContactMessagePayload
type ContactMessagePayload struct {
	To string `json:"to"`
	Vcard ContactMessagePayloadVcard `json:"vcard"`
}

// NewContactMessagePayload instantiates a new ContactMessagePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContactMessagePayload(to string, vcard ContactMessagePayloadVcard) *ContactMessagePayload {
	this := ContactMessagePayload{}
	this.To = to
	this.Vcard = vcard
	return &this
}

// NewContactMessagePayloadWithDefaults instantiates a new ContactMessagePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContactMessagePayloadWithDefaults() *ContactMessagePayload {
	this := ContactMessagePayload{}
	return &this
}

// GetTo returns the To field value
func (o *ContactMessagePayload) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *ContactMessagePayload) GetToOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *ContactMessagePayload) SetTo(v string) {
	o.To = v
}

// GetVcard returns the Vcard field value
func (o *ContactMessagePayload) GetVcard() ContactMessagePayloadVcard {
	if o == nil {
		var ret ContactMessagePayloadVcard
		return ret
	}

	return o.Vcard
}

// GetVcardOk returns a tuple with the Vcard field value
// and a boolean to check if the value has been set.
func (o *ContactMessagePayload) GetVcardOk() (*ContactMessagePayloadVcard, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Vcard, true
}

// SetVcard sets field value
func (o *ContactMessagePayload) SetVcard(v ContactMessagePayloadVcard) {
	o.Vcard = v
}

func (o ContactMessagePayload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["to"] = o.To
	}
	if true {
		toSerialize["vcard"] = o.Vcard
	}
	return json.Marshal(toSerialize)
}

type NullableContactMessagePayload struct {
	value *ContactMessagePayload
	isSet bool
}

func (v NullableContactMessagePayload) Get() *ContactMessagePayload {
	return v.value
}

func (v *NullableContactMessagePayload) Set(val *ContactMessagePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableContactMessagePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableContactMessagePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContactMessagePayload(val *ContactMessagePayload) *NullableContactMessagePayload {
	return &NullableContactMessagePayload{value: val, isSet: true}
}

func (v NullableContactMessagePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContactMessagePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


