/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package WhatsAPI

import (
	"encoding/json"
	"os"
)

// InstancesInstanceKeySendUploadPostRequest struct for InstancesInstanceKeySendUploadPostRequest
type InstancesInstanceKeySendUploadPostRequest struct {
	// Media file
	File *os.File `json:"file"`
}

// NewInstancesInstanceKeySendUploadPostRequest instantiates a new InstancesInstanceKeySendUploadPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstancesInstanceKeySendUploadPostRequest(file *os.File) *InstancesInstanceKeySendUploadPostRequest {
	this := InstancesInstanceKeySendUploadPostRequest{}
	this.File = file
	return &this
}

// NewInstancesInstanceKeySendUploadPostRequestWithDefaults instantiates a new InstancesInstanceKeySendUploadPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstancesInstanceKeySendUploadPostRequestWithDefaults() *InstancesInstanceKeySendUploadPostRequest {
	this := InstancesInstanceKeySendUploadPostRequest{}
	return &this
}

// GetFile returns the File field value
func (o *InstancesInstanceKeySendUploadPostRequest) GetFile() *os.File {
	if o == nil {
		var ret *os.File
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *InstancesInstanceKeySendUploadPostRequest) GetFileOk() (**os.File, bool) {
	if o == nil {
    return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *InstancesInstanceKeySendUploadPostRequest) SetFile(v *os.File) {
	o.File = v
}

func (o InstancesInstanceKeySendUploadPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["file"] = o.File
	}
	return json.Marshal(toSerialize)
}

type NullableInstancesInstanceKeySendUploadPostRequest struct {
	value *InstancesInstanceKeySendUploadPostRequest
	isSet bool
}

func (v NullableInstancesInstanceKeySendUploadPostRequest) Get() *InstancesInstanceKeySendUploadPostRequest {
	return v.value
}

func (v *NullableInstancesInstanceKeySendUploadPostRequest) Set(val *InstancesInstanceKeySendUploadPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInstancesInstanceKeySendUploadPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInstancesInstanceKeySendUploadPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstancesInstanceKeySendUploadPostRequest(val *InstancesInstanceKeySendUploadPostRequest) *NullableInstancesInstanceKeySendUploadPostRequest {
	return &NullableInstancesInstanceKeySendUploadPostRequest{value: val, isSet: true}
}

func (v NullableInstancesInstanceKeySendUploadPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstancesInstanceKeySendUploadPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


