/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package WhatsAPI

import (
	"encoding/json"
)

// PollMessagePayload struct for PollMessagePayload
type PollMessagePayload struct {
	Options []string `json:"options"`
	SelectableOptionsCount int32 `json:"selectable_options_count"`
	Title string `json:"title"`
	To string `json:"to"`
}

// NewPollMessagePayload instantiates a new PollMessagePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPollMessagePayload(options []string, selectableOptionsCount int32, title string, to string) *PollMessagePayload {
	this := PollMessagePayload{}
	this.Options = options
	this.SelectableOptionsCount = selectableOptionsCount
	this.Title = title
	this.To = to
	return &this
}

// NewPollMessagePayloadWithDefaults instantiates a new PollMessagePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPollMessagePayloadWithDefaults() *PollMessagePayload {
	this := PollMessagePayload{}
	return &this
}

// GetOptions returns the Options field value
func (o *PollMessagePayload) GetOptions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *PollMessagePayload) GetOptionsOk() ([]string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Options, true
}

// SetOptions sets field value
func (o *PollMessagePayload) SetOptions(v []string) {
	o.Options = v
}

// GetSelectableOptionsCount returns the SelectableOptionsCount field value
func (o *PollMessagePayload) GetSelectableOptionsCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SelectableOptionsCount
}

// GetSelectableOptionsCountOk returns a tuple with the SelectableOptionsCount field value
// and a boolean to check if the value has been set.
func (o *PollMessagePayload) GetSelectableOptionsCountOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.SelectableOptionsCount, true
}

// SetSelectableOptionsCount sets field value
func (o *PollMessagePayload) SetSelectableOptionsCount(v int32) {
	o.SelectableOptionsCount = v
}

// GetTitle returns the Title field value
func (o *PollMessagePayload) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *PollMessagePayload) GetTitleOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *PollMessagePayload) SetTitle(v string) {
	o.Title = v
}

// GetTo returns the To field value
func (o *PollMessagePayload) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *PollMessagePayload) GetToOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *PollMessagePayload) SetTo(v string) {
	o.To = v
}

func (o PollMessagePayload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["options"] = o.Options
	}
	if true {
		toSerialize["selectable_options_count"] = o.SelectableOptionsCount
	}
	if true {
		toSerialize["title"] = o.Title
	}
	if true {
		toSerialize["to"] = o.To
	}
	return json.Marshal(toSerialize)
}

type NullablePollMessagePayload struct {
	value *PollMessagePayload
	isSet bool
}

func (v NullablePollMessagePayload) Get() *PollMessagePayload {
	return v.value
}

func (v *NullablePollMessagePayload) Set(val *PollMessagePayload) {
	v.value = val
	v.isSet = true
}

func (v NullablePollMessagePayload) IsSet() bool {
	return v.isSet
}

func (v *NullablePollMessagePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePollMessagePayload(val *PollMessagePayload) *NullablePollMessagePayload {
	return &NullablePollMessagePayload{value: val, isSet: true}
}

func (v NullablePollMessagePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePollMessagePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


