/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package WhatsAPI

import (
	"encoding/json"
	"os"
)

// SendVideoRequest struct for SendVideoRequest
type SendVideoRequest struct {
	// Video file
	File *os.File `json:"file"`
}

// NewSendVideoRequest instantiates a new SendVideoRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendVideoRequest(file *os.File) *SendVideoRequest {
	this := SendVideoRequest{}
	this.File = file
	return &this
}

// NewSendVideoRequestWithDefaults instantiates a new SendVideoRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendVideoRequestWithDefaults() *SendVideoRequest {
	this := SendVideoRequest{}
	return &this
}

// GetFile returns the File field value
func (o *SendVideoRequest) GetFile() *os.File {
	if o == nil {
		var ret *os.File
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *SendVideoRequest) GetFileOk() (**os.File, bool) {
	if o == nil {
    return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *SendVideoRequest) SetFile(v *os.File) {
	o.File = v
}

func (o SendVideoRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["file"] = o.File
	}
	return json.Marshal(toSerialize)
}

type NullableSendVideoRequest struct {
	value *SendVideoRequest
	isSet bool
}

func (v NullableSendVideoRequest) Get() *SendVideoRequest {
	return v.value
}

func (v *NullableSendVideoRequest) Set(val *SendVideoRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSendVideoRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSendVideoRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendVideoRequest(val *SendVideoRequest) *NullableSendVideoRequest {
	return &NullableSendVideoRequest{value: val, isSet: true}
}

func (v NullableSendVideoRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendVideoRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


