/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"os"
)

// InstancesInstanceKeySendAudioPostRequest struct for InstancesInstanceKeySendAudioPostRequest
type InstancesInstanceKeySendAudioPostRequest struct {
	// Audio file
	File *os.File `json:"file"`
}

// NewInstancesInstanceKeySendAudioPostRequest instantiates a new InstancesInstanceKeySendAudioPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstancesInstanceKeySendAudioPostRequest(file *os.File) *InstancesInstanceKeySendAudioPostRequest {
	this := InstancesInstanceKeySendAudioPostRequest{}
	this.File = file
	return &this
}

// NewInstancesInstanceKeySendAudioPostRequestWithDefaults instantiates a new InstancesInstanceKeySendAudioPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstancesInstanceKeySendAudioPostRequestWithDefaults() *InstancesInstanceKeySendAudioPostRequest {
	this := InstancesInstanceKeySendAudioPostRequest{}
	return &this
}

// GetFile returns the File field value
func (o *InstancesInstanceKeySendAudioPostRequest) GetFile() *os.File {
	if o == nil {
		var ret *os.File
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *InstancesInstanceKeySendAudioPostRequest) GetFileOk() (**os.File, bool) {
	if o == nil {
    return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *InstancesInstanceKeySendAudioPostRequest) SetFile(v *os.File) {
	o.File = v
}

func (o InstancesInstanceKeySendAudioPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["file"] = o.File
	}
	return json.Marshal(toSerialize)
}

type NullableInstancesInstanceKeySendAudioPostRequest struct {
	value *InstancesInstanceKeySendAudioPostRequest
	isSet bool
}

func (v NullableInstancesInstanceKeySendAudioPostRequest) Get() *InstancesInstanceKeySendAudioPostRequest {
	return v.value
}

func (v *NullableInstancesInstanceKeySendAudioPostRequest) Set(val *InstancesInstanceKeySendAudioPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInstancesInstanceKeySendAudioPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInstancesInstanceKeySendAudioPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstancesInstanceKeySendAudioPostRequest(val *InstancesInstanceKeySendAudioPostRequest) *NullableInstancesInstanceKeySendAudioPostRequest {
	return &NullableInstancesInstanceKeySendAudioPostRequest{value: val, isSet: true}
}

func (v NullableInstancesInstanceKeySendAudioPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstancesInstanceKeySendAudioPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


