/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package WhatsAPI

import (
	"encoding/json"
	"os"
)

// SendImageRequest struct for SendImageRequest
type SendImageRequest struct {
	// Image file
	File *os.File `json:"file"`
}

// NewSendImageRequest instantiates a new SendImageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendImageRequest(file *os.File) *SendImageRequest {
	this := SendImageRequest{}
	this.File = file
	return &this
}

// NewSendImageRequestWithDefaults instantiates a new SendImageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendImageRequestWithDefaults() *SendImageRequest {
	this := SendImageRequest{}
	return &this
}

// GetFile returns the File field value
func (o *SendImageRequest) GetFile() *os.File {
	if o == nil {
		var ret *os.File
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *SendImageRequest) GetFileOk() (**os.File, bool) {
	if o == nil {
    return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *SendImageRequest) SetFile(v *os.File) {
	o.File = v
}

func (o SendImageRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["file"] = o.File
	}
	return json.Marshal(toSerialize)
}

type NullableSendImageRequest struct {
	value *SendImageRequest
	isSet bool
}

func (v NullableSendImageRequest) Get() *SendImageRequest {
	return v.value
}

func (v *NullableSendImageRequest) Set(val *SendImageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSendImageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSendImageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendImageRequest(val *SendImageRequest) *NullableSendImageRequest {
	return &NullableSendImageRequest{value: val, isSet: true}
}

func (v NullableSendImageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendImageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


