/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package WhatsAPI

import (
	"encoding/json"
	"os"
)

// SendAudioRequest struct for SendAudioRequest
type SendAudioRequest struct {
	// Audio file
	File *os.File `json:"file"`
}

// NewSendAudioRequest instantiates a new SendAudioRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendAudioRequest(file *os.File) *SendAudioRequest {
	this := SendAudioRequest{}
	this.File = file
	return &this
}

// NewSendAudioRequestWithDefaults instantiates a new SendAudioRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendAudioRequestWithDefaults() *SendAudioRequest {
	this := SendAudioRequest{}
	return &this
}

// GetFile returns the File field value
func (o *SendAudioRequest) GetFile() *os.File {
	if o == nil {
		var ret *os.File
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *SendAudioRequest) GetFileOk() (**os.File, bool) {
	if o == nil {
    return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *SendAudioRequest) SetFile(v *os.File) {
	o.File = v
}

func (o SendAudioRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["file"] = o.File
	}
	return json.Marshal(toSerialize)
}

type NullableSendAudioRequest struct {
	value *SendAudioRequest
	isSet bool
}

func (v NullableSendAudioRequest) Get() *SendAudioRequest {
	return v.value
}

func (v *NullableSendAudioRequest) Set(val *SendAudioRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSendAudioRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSendAudioRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendAudioRequest(val *SendAudioRequest) *NullableSendAudioRequest {
	return &NullableSendAudioRequest{value: val, isSet: true}
}

func (v NullableSendAudioRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendAudioRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


