/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whatsapi

import (
	"encoding/json"
)

// StructsGroupUpdateParticipantsPayload struct for StructsGroupUpdateParticipantsPayload
type StructsGroupUpdateParticipantsPayload struct {
	Participants []string `json:"participants,omitempty"`
}

// NewStructsGroupUpdateParticipantsPayload instantiates a new StructsGroupUpdateParticipantsPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStructsGroupUpdateParticipantsPayload() *StructsGroupUpdateParticipantsPayload {
	this := StructsGroupUpdateParticipantsPayload{}
	return &this
}

// NewStructsGroupUpdateParticipantsPayloadWithDefaults instantiates a new StructsGroupUpdateParticipantsPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStructsGroupUpdateParticipantsPayloadWithDefaults() *StructsGroupUpdateParticipantsPayload {
	this := StructsGroupUpdateParticipantsPayload{}
	return &this
}

// GetParticipants returns the Participants field value if set, zero value otherwise.
func (o *StructsGroupUpdateParticipantsPayload) GetParticipants() []string {
	if o == nil || isNil(o.Participants) {
		var ret []string
		return ret
	}
	return o.Participants
}

// GetParticipantsOk returns a tuple with the Participants field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StructsGroupUpdateParticipantsPayload) GetParticipantsOk() ([]string, bool) {
	if o == nil || isNil(o.Participants) {
    return nil, false
	}
	return o.Participants, true
}

// HasParticipants returns a boolean if a field has been set.
func (o *StructsGroupUpdateParticipantsPayload) HasParticipants() bool {
	if o != nil && !isNil(o.Participants) {
		return true
	}

	return false
}

// SetParticipants gets a reference to the given []string and assigns it to the Participants field.
func (o *StructsGroupUpdateParticipantsPayload) SetParticipants(v []string) {
	o.Participants = v
}

func (o StructsGroupUpdateParticipantsPayload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Participants) {
		toSerialize["participants"] = o.Participants
	}
	return json.Marshal(toSerialize)
}

type NullableStructsGroupUpdateParticipantsPayload struct {
	value *StructsGroupUpdateParticipantsPayload
	isSet bool
}

func (v NullableStructsGroupUpdateParticipantsPayload) Get() *StructsGroupUpdateParticipantsPayload {
	return v.value
}

func (v *NullableStructsGroupUpdateParticipantsPayload) Set(val *StructsGroupUpdateParticipantsPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableStructsGroupUpdateParticipantsPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableStructsGroupUpdateParticipantsPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStructsGroupUpdateParticipantsPayload(val *StructsGroupUpdateParticipantsPayload) *NullableStructsGroupUpdateParticipantsPayload {
	return &NullableStructsGroupUpdateParticipantsPayload{value: val, isSet: true}
}

func (v NullableStructsGroupUpdateParticipantsPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStructsGroupUpdateParticipantsPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


