/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package WhatsAPI

import (
	"encoding/json"
)

// LocationMessagePayload struct for LocationMessagePayload
type LocationMessagePayload struct {
	Location LocationMessagePayloadLocation `json:"location"`
	To string `json:"to"`
	Url *string `json:"url,omitempty"`
}

// NewLocationMessagePayload instantiates a new LocationMessagePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocationMessagePayload(location LocationMessagePayloadLocation, to string) *LocationMessagePayload {
	this := LocationMessagePayload{}
	this.Location = location
	this.To = to
	return &this
}

// NewLocationMessagePayloadWithDefaults instantiates a new LocationMessagePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocationMessagePayloadWithDefaults() *LocationMessagePayload {
	this := LocationMessagePayload{}
	return &this
}

// GetLocation returns the Location field value
func (o *LocationMessagePayload) GetLocation() LocationMessagePayloadLocation {
	if o == nil {
		var ret LocationMessagePayloadLocation
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *LocationMessagePayload) GetLocationOk() (*LocationMessagePayloadLocation, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *LocationMessagePayload) SetLocation(v LocationMessagePayloadLocation) {
	o.Location = v
}

// GetTo returns the To field value
func (o *LocationMessagePayload) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *LocationMessagePayload) GetToOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *LocationMessagePayload) SetTo(v string) {
	o.To = v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *LocationMessagePayload) GetUrl() string {
	if o == nil || isNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocationMessagePayload) GetUrlOk() (*string, bool) {
	if o == nil || isNil(o.Url) {
    return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *LocationMessagePayload) HasUrl() bool {
	if o != nil && !isNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *LocationMessagePayload) SetUrl(v string) {
	o.Url = &v
}

func (o LocationMessagePayload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["location"] = o.Location
	}
	if true {
		toSerialize["to"] = o.To
	}
	if !isNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return json.Marshal(toSerialize)
}

type NullableLocationMessagePayload struct {
	value *LocationMessagePayload
	isSet bool
}

func (v NullableLocationMessagePayload) Get() *LocationMessagePayload {
	return v.value
}

func (v *NullableLocationMessagePayload) Set(val *LocationMessagePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableLocationMessagePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableLocationMessagePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocationMessagePayload(val *LocationMessagePayload) *NullableLocationMessagePayload {
	return &NullableLocationMessagePayload{value: val, isSet: true}
}

func (v NullableLocationMessagePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocationMessagePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


