/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package com.whatsapi

import (
	"encoding/json"
)

// StructsContactMessagePayload struct for StructsContactMessagePayload
type StructsContactMessagePayload struct {
	To string `json:"to"`
	Vcard StructsContactMessagePayloadVcard `json:"vcard"`
}

// NewStructsContactMessagePayload instantiates a new StructsContactMessagePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStructsContactMessagePayload(to string, vcard StructsContactMessagePayloadVcard) *StructsContactMessagePayload {
	this := StructsContactMessagePayload{}
	this.To = to
	this.Vcard = vcard
	return &this
}

// NewStructsContactMessagePayloadWithDefaults instantiates a new StructsContactMessagePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStructsContactMessagePayloadWithDefaults() *StructsContactMessagePayload {
	this := StructsContactMessagePayload{}
	return &this
}

// GetTo returns the To field value
func (o *StructsContactMessagePayload) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *StructsContactMessagePayload) GetToOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *StructsContactMessagePayload) SetTo(v string) {
	o.To = v
}

// GetVcard returns the Vcard field value
func (o *StructsContactMessagePayload) GetVcard() StructsContactMessagePayloadVcard {
	if o == nil {
		var ret StructsContactMessagePayloadVcard
		return ret
	}

	return o.Vcard
}

// GetVcardOk returns a tuple with the Vcard field value
// and a boolean to check if the value has been set.
func (o *StructsContactMessagePayload) GetVcardOk() (*StructsContactMessagePayloadVcard, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Vcard, true
}

// SetVcard sets field value
func (o *StructsContactMessagePayload) SetVcard(v StructsContactMessagePayloadVcard) {
	o.Vcard = v
}

func (o StructsContactMessagePayload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["to"] = o.To
	}
	if true {
		toSerialize["vcard"] = o.Vcard
	}
	return json.Marshal(toSerialize)
}

type NullableStructsContactMessagePayload struct {
	value *StructsContactMessagePayload
	isSet bool
}

func (v NullableStructsContactMessagePayload) Get() *StructsContactMessagePayload {
	return v.value
}

func (v *NullableStructsContactMessagePayload) Set(val *StructsContactMessagePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableStructsContactMessagePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableStructsContactMessagePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStructsContactMessagePayload(val *StructsContactMessagePayload) *NullableStructsContactMessagePayload {
	return &NullableStructsContactMessagePayload{value: val, isSet: true}
}

func (v NullableStructsContactMessagePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStructsContactMessagePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


