/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package WhatsAPI

import (
	"encoding/json"
)

// GroupUpdateParticipantsPayload struct for GroupUpdateParticipantsPayload
type GroupUpdateParticipantsPayload struct {
	Participants []string `json:"participants,omitempty"`
}

// NewGroupUpdateParticipantsPayload instantiates a new GroupUpdateParticipantsPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupUpdateParticipantsPayload() *GroupUpdateParticipantsPayload {
	this := GroupUpdateParticipantsPayload{}
	return &this
}

// NewGroupUpdateParticipantsPayloadWithDefaults instantiates a new GroupUpdateParticipantsPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupUpdateParticipantsPayloadWithDefaults() *GroupUpdateParticipantsPayload {
	this := GroupUpdateParticipantsPayload{}
	return &this
}

// GetParticipants returns the Participants field value if set, zero value otherwise.
func (o *GroupUpdateParticipantsPayload) GetParticipants() []string {
	if o == nil || isNil(o.Participants) {
		var ret []string
		return ret
	}
	return o.Participants
}

// GetParticipantsOk returns a tuple with the Participants field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupUpdateParticipantsPayload) GetParticipantsOk() ([]string, bool) {
	if o == nil || isNil(o.Participants) {
    return nil, false
	}
	return o.Participants, true
}

// HasParticipants returns a boolean if a field has been set.
func (o *GroupUpdateParticipantsPayload) HasParticipants() bool {
	if o != nil && !isNil(o.Participants) {
		return true
	}

	return false
}

// SetParticipants gets a reference to the given []string and assigns it to the Participants field.
func (o *GroupUpdateParticipantsPayload) SetParticipants(v []string) {
	o.Participants = v
}

func (o GroupUpdateParticipantsPayload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Participants) {
		toSerialize["participants"] = o.Participants
	}
	return json.Marshal(toSerialize)
}

type NullableGroupUpdateParticipantsPayload struct {
	value *GroupUpdateParticipantsPayload
	isSet bool
}

func (v NullableGroupUpdateParticipantsPayload) Get() *GroupUpdateParticipantsPayload {
	return v.value
}

func (v *NullableGroupUpdateParticipantsPayload) Set(val *GroupUpdateParticipantsPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupUpdateParticipantsPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupUpdateParticipantsPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupUpdateParticipantsPayload(val *GroupUpdateParticipantsPayload) *NullableGroupUpdateParticipantsPayload {
	return &NullableGroupUpdateParticipantsPayload{value: val, isSet: true}
}

func (v NullableGroupUpdateParticipantsPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupUpdateParticipantsPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


