/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package WhatsAPI

import (
	"encoding/json"
)

// PaymentRequestPayload struct for PaymentRequestPayload
type PaymentRequestPayload struct {
	Amount *int32 `json:"amount,omitempty"`
	Currency *string `json:"currency,omitempty"`
	ExpiryMinutes *int32 `json:"expiry_minutes,omitempty"`
	To *string `json:"to,omitempty"`
}

// NewPaymentRequestPayload instantiates a new PaymentRequestPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentRequestPayload() *PaymentRequestPayload {
	this := PaymentRequestPayload{}
	return &this
}

// NewPaymentRequestPayloadWithDefaults instantiates a new PaymentRequestPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentRequestPayloadWithDefaults() *PaymentRequestPayload {
	this := PaymentRequestPayload{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *PaymentRequestPayload) GetAmount() int32 {
	if o == nil || isNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRequestPayload) GetAmountOk() (*int32, bool) {
	if o == nil || isNil(o.Amount) {
    return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *PaymentRequestPayload) HasAmount() bool {
	if o != nil && !isNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *PaymentRequestPayload) SetAmount(v int32) {
	o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *PaymentRequestPayload) GetCurrency() string {
	if o == nil || isNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRequestPayload) GetCurrencyOk() (*string, bool) {
	if o == nil || isNil(o.Currency) {
    return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *PaymentRequestPayload) HasCurrency() bool {
	if o != nil && !isNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *PaymentRequestPayload) SetCurrency(v string) {
	o.Currency = &v
}

// GetExpiryMinutes returns the ExpiryMinutes field value if set, zero value otherwise.
func (o *PaymentRequestPayload) GetExpiryMinutes() int32 {
	if o == nil || isNil(o.ExpiryMinutes) {
		var ret int32
		return ret
	}
	return *o.ExpiryMinutes
}

// GetExpiryMinutesOk returns a tuple with the ExpiryMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRequestPayload) GetExpiryMinutesOk() (*int32, bool) {
	if o == nil || isNil(o.ExpiryMinutes) {
    return nil, false
	}
	return o.ExpiryMinutes, true
}

// HasExpiryMinutes returns a boolean if a field has been set.
func (o *PaymentRequestPayload) HasExpiryMinutes() bool {
	if o != nil && !isNil(o.ExpiryMinutes) {
		return true
	}

	return false
}

// SetExpiryMinutes gets a reference to the given int32 and assigns it to the ExpiryMinutes field.
func (o *PaymentRequestPayload) SetExpiryMinutes(v int32) {
	o.ExpiryMinutes = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *PaymentRequestPayload) GetTo() string {
	if o == nil || isNil(o.To) {
		var ret string
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRequestPayload) GetToOk() (*string, bool) {
	if o == nil || isNil(o.To) {
    return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *PaymentRequestPayload) HasTo() bool {
	if o != nil && !isNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given string and assigns it to the To field.
func (o *PaymentRequestPayload) SetTo(v string) {
	o.To = &v
}

func (o PaymentRequestPayload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !isNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !isNil(o.ExpiryMinutes) {
		toSerialize["expiry_minutes"] = o.ExpiryMinutes
	}
	if !isNil(o.To) {
		toSerialize["to"] = o.To
	}
	return json.Marshal(toSerialize)
}

type NullablePaymentRequestPayload struct {
	value *PaymentRequestPayload
	isSet bool
}

func (v NullablePaymentRequestPayload) Get() *PaymentRequestPayload {
	return v.value
}

func (v *NullablePaymentRequestPayload) Set(val *PaymentRequestPayload) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentRequestPayload) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentRequestPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentRequestPayload(val *PaymentRequestPayload) *NullablePaymentRequestPayload {
	return &NullablePaymentRequestPayload{value: val, isSet: true}
}

func (v NullablePaymentRequestPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentRequestPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


