/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package com.whatsapi

import (
	"encoding/json"
)

// StructsGroupUpdateNamePayload struct for StructsGroupUpdateNamePayload
type StructsGroupUpdateNamePayload struct {
	Name *string `json:"name,omitempty"`
}

// NewStructsGroupUpdateNamePayload instantiates a new StructsGroupUpdateNamePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStructsGroupUpdateNamePayload() *StructsGroupUpdateNamePayload {
	this := StructsGroupUpdateNamePayload{}
	return &this
}

// NewStructsGroupUpdateNamePayloadWithDefaults instantiates a new StructsGroupUpdateNamePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStructsGroupUpdateNamePayloadWithDefaults() *StructsGroupUpdateNamePayload {
	this := StructsGroupUpdateNamePayload{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *StructsGroupUpdateNamePayload) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StructsGroupUpdateNamePayload) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *StructsGroupUpdateNamePayload) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *StructsGroupUpdateNamePayload) SetName(v string) {
	o.Name = &v
}

func (o StructsGroupUpdateNamePayload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableStructsGroupUpdateNamePayload struct {
	value *StructsGroupUpdateNamePayload
	isSet bool
}

func (v NullableStructsGroupUpdateNamePayload) Get() *StructsGroupUpdateNamePayload {
	return v.value
}

func (v *NullableStructsGroupUpdateNamePayload) Set(val *StructsGroupUpdateNamePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableStructsGroupUpdateNamePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableStructsGroupUpdateNamePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStructsGroupUpdateNamePayload(val *StructsGroupUpdateNamePayload) *NullableStructsGroupUpdateNamePayload {
	return &NullableStructsGroupUpdateNamePayload{value: val, isSet: true}
}

func (v NullableStructsGroupUpdateNamePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStructsGroupUpdateNamePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


