/*
WhatsAPI Go

The V2 of WhatsAPI Go

API version: 2.0
Contact: manjit@sponsorbook.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package WhatsAPI

import (
	"encoding/json"
)

// StructsTemplateButtonWithMediaPayload struct for StructsTemplateButtonWithMediaPayload
type StructsTemplateButtonWithMediaPayload struct {
	Buttons []StructsTemplateButton `json:"buttons"`
	ContentText *string `json:"content_text,omitempty"`
	Footer *string `json:"footer,omitempty"`
	Media StructsFileUpload `json:"media"`
	To string `json:"to"`
}

// NewStructsTemplateButtonWithMediaPayload instantiates a new StructsTemplateButtonWithMediaPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStructsTemplateButtonWithMediaPayload(buttons []StructsTemplateButton, media StructsFileUpload, to string) *StructsTemplateButtonWithMediaPayload {
	this := StructsTemplateButtonWithMediaPayload{}
	this.Buttons = buttons
	this.Media = media
	this.To = to
	return &this
}

// NewStructsTemplateButtonWithMediaPayloadWithDefaults instantiates a new StructsTemplateButtonWithMediaPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStructsTemplateButtonWithMediaPayloadWithDefaults() *StructsTemplateButtonWithMediaPayload {
	this := StructsTemplateButtonWithMediaPayload{}
	return &this
}

// GetButtons returns the Buttons field value
func (o *StructsTemplateButtonWithMediaPayload) GetButtons() []StructsTemplateButton {
	if o == nil {
		var ret []StructsTemplateButton
		return ret
	}

	return o.Buttons
}

// GetButtonsOk returns a tuple with the Buttons field value
// and a boolean to check if the value has been set.
func (o *StructsTemplateButtonWithMediaPayload) GetButtonsOk() ([]StructsTemplateButton, bool) {
	if o == nil {
    return nil, false
	}
	return o.Buttons, true
}

// SetButtons sets field value
func (o *StructsTemplateButtonWithMediaPayload) SetButtons(v []StructsTemplateButton) {
	o.Buttons = v
}

// GetContentText returns the ContentText field value if set, zero value otherwise.
func (o *StructsTemplateButtonWithMediaPayload) GetContentText() string {
	if o == nil || isNil(o.ContentText) {
		var ret string
		return ret
	}
	return *o.ContentText
}

// GetContentTextOk returns a tuple with the ContentText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StructsTemplateButtonWithMediaPayload) GetContentTextOk() (*string, bool) {
	if o == nil || isNil(o.ContentText) {
    return nil, false
	}
	return o.ContentText, true
}

// HasContentText returns a boolean if a field has been set.
func (o *StructsTemplateButtonWithMediaPayload) HasContentText() bool {
	if o != nil && !isNil(o.ContentText) {
		return true
	}

	return false
}

// SetContentText gets a reference to the given string and assigns it to the ContentText field.
func (o *StructsTemplateButtonWithMediaPayload) SetContentText(v string) {
	o.ContentText = &v
}

// GetFooter returns the Footer field value if set, zero value otherwise.
func (o *StructsTemplateButtonWithMediaPayload) GetFooter() string {
	if o == nil || isNil(o.Footer) {
		var ret string
		return ret
	}
	return *o.Footer
}

// GetFooterOk returns a tuple with the Footer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StructsTemplateButtonWithMediaPayload) GetFooterOk() (*string, bool) {
	if o == nil || isNil(o.Footer) {
    return nil, false
	}
	return o.Footer, true
}

// HasFooter returns a boolean if a field has been set.
func (o *StructsTemplateButtonWithMediaPayload) HasFooter() bool {
	if o != nil && !isNil(o.Footer) {
		return true
	}

	return false
}

// SetFooter gets a reference to the given string and assigns it to the Footer field.
func (o *StructsTemplateButtonWithMediaPayload) SetFooter(v string) {
	o.Footer = &v
}

// GetMedia returns the Media field value
func (o *StructsTemplateButtonWithMediaPayload) GetMedia() StructsFileUpload {
	if o == nil {
		var ret StructsFileUpload
		return ret
	}

	return o.Media
}

// GetMediaOk returns a tuple with the Media field value
// and a boolean to check if the value has been set.
func (o *StructsTemplateButtonWithMediaPayload) GetMediaOk() (*StructsFileUpload, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Media, true
}

// SetMedia sets field value
func (o *StructsTemplateButtonWithMediaPayload) SetMedia(v StructsFileUpload) {
	o.Media = v
}

// GetTo returns the To field value
func (o *StructsTemplateButtonWithMediaPayload) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *StructsTemplateButtonWithMediaPayload) GetToOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *StructsTemplateButtonWithMediaPayload) SetTo(v string) {
	o.To = v
}

func (o StructsTemplateButtonWithMediaPayload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["buttons"] = o.Buttons
	}
	if !isNil(o.ContentText) {
		toSerialize["content_text"] = o.ContentText
	}
	if !isNil(o.Footer) {
		toSerialize["footer"] = o.Footer
	}
	if true {
		toSerialize["media"] = o.Media
	}
	if true {
		toSerialize["to"] = o.To
	}
	return json.Marshal(toSerialize)
}

type NullableStructsTemplateButtonWithMediaPayload struct {
	value *StructsTemplateButtonWithMediaPayload
	isSet bool
}

func (v NullableStructsTemplateButtonWithMediaPayload) Get() *StructsTemplateButtonWithMediaPayload {
	return v.value
}

func (v *NullableStructsTemplateButtonWithMediaPayload) Set(val *StructsTemplateButtonWithMediaPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableStructsTemplateButtonWithMediaPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableStructsTemplateButtonWithMediaPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStructsTemplateButtonWithMediaPayload(val *StructsTemplateButtonWithMediaPayload) *NullableStructsTemplateButtonWithMediaPayload {
	return &NullableStructsTemplateButtonWithMediaPayload{value: val, isSet: true}
}

func (v NullableStructsTemplateButtonWithMediaPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStructsTemplateButtonWithMediaPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


